AWSTemplateFormatVersion: '2010-09-09'
Description: Server EC2 cu security group

Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

  GeminiApiKey:
    Type: String
    NoEcho: true
    Description: Cheia API Gemini

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and ICMP
      VpcId: !ImportValue network-vpc-id
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 5.12.234.139/32
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 81.196.21.110/32
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref LatestAmiId
      KeyName: "frankfurt"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > /var/log/user-data.log 2>&1
          set -e -x
          yum update -y
          yum install nginx python3 python3-pip git -y
          pip3 install --break-system-packages flask google-generativeai boto3
          git clone https://github.com/AndreeaV13/awsinfra.git /var/www/app

          cat > /etc/systemd/system/flask.service << 'SYSTEMD_EOF'
          [Unit]
          Description=Flask App
          After=network.target

          [Service]
          WorkingDirectory=/var/www/app
          Environment="GEMINI_API_KEY=${GeminiApiKey}"
          ExecStart=/usr/bin/python3 /var/www/app/app.py
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target
          SYSTEMD_EOF

          systemctl daemon-reload
          systemctl enable flask
          systemctl start flask
          systemctl start nginx
          systemctl enable nginx
      Tags:
        - Key: Name
          Value: first-ec2-instance
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref InstanceSecurityGroup
          SubnetId: !ImportValue network-subnet3-id

Outputs:
  InstanceId:
    Value: !Ref WebServerInstance
  PublicIP:
    Value: !GetAtt WebServerInstance.PublicIp